"""
Semantic Memory — Interactive initialization script.

Run this once per agent workspace to configure connection to a Supabase backend.

Usage:
    python -m semantic_memory.init

Or from Python:
    from semantic_memory.init import run_init
    run_init()
"""
from __future__ import annotations

import getpass
import os
import re
import sys
import uuid
from pathlib import Path

import httpx


def _input_required(prompt: str) -> str:
    while True:
        value = input(prompt).strip()
        if value:
            return value
        print("  This field is required.")


def _extract_project_ref(url: str) -> str | None:
    m = re.match(r"https://([a-z0-9_-]+)\.supabase\.co", url.lower())
    if m:
        return m.group(1)
    return None


def _call_init_edge_function(url: str, anon_key: str) -> dict:
    """Call the /init Edge Function to check database state."""
    # We need a valid JWT. For a fresh project we may not have a user yet,
    # so we use the anon key itself in the Authorization header.
    # The init function only checks header presence, not JWT validity.
    resp = httpx.post(
        f"{url}/functions/v1/init",
        headers={
            "Authorization": f"Bearer {anon_key}",
            "Content-Type": "application/json",
        },
        json={},
        timeout=30.0,
    )
    resp.raise_for_status()
    return resp.json()


def _apply_migration_via_api(
    project_ref: str, pat: str, migration_name: str, sql: str
) -> bool:
    """Try to apply a migration via Supabase Management API."""
    try:
        resp = httpx.post(
            f"https://api.supabase.com/v1/projects/{project_ref}/database/migrations",
            headers={
                "Authorization": f"Bearer {pat}",
                "Content-Type": "application/json",
            },
            json={"query": sql, "name": migration_name},
            timeout=60.0,
        )
        if resp.status_code in (200, 201):
            print(f"    Applied {migration_name}")
            return True
        if resp.status_code == 403:
            print(f"    Management API returned 403 for {migration_name} — PAT may not have migration access.")
            return False
        print(f"    Failed to apply {migration_name}: HTTP {resp.status_code} — {resp.text}")
        return False
    except Exception as e:
        print(f"    Error applying {migration_name}: {e}")
        return False


def _find_migrations() -> list[tuple[str, str]]:
    """Find migration SQL files locally. Returns [(name, sql), ...]."""
    # Try several possible locations relative to this file
    candidates = [
        Path(__file__).parent.parent.parent / "supabase" / "migrations",
        Path(__file__).parent.parent / "supabase" / "migrations",
        Path.cwd() / "supabase" / "migrations",
    ]
    for migrations_dir in candidates:
        if migrations_dir.exists():
            files = sorted(migrations_dir.glob("*.sql"))
            result = []
            for f in files:
                result.append((f.name, f.read_text(encoding="utf-8")))
            return result
    return []


def _create_env_file(
    env_path: Path,
    url: str,
    anon_key: str,
    email: str,
    password: str,
    session_id: str = "",
) -> None:
    lines = [
        "# Semantic Memory — Environment Variables",
        "# Generated by semantic-memory init script",
        "",
        f"SUPABASE_URL={url}",
        f"SUPABASE_ANON_KEY={anon_key}",
        "",
        "# Shared agent credentials (all agents use the same account)",
        f"AGENT_EMAIL={email}",
        f"AGENT_PASSWORD={password}",
        "",
        "# Session ID (optional — leave blank to auto-generate)",
        f"AGENT_SESSION_ID={session_id}",
        "",
        "# agent_name is NOT set here — it is passed in every API call.",
    ]
    env_path.write_text("\n".join(lines), encoding="utf-8")


def run_init() -> None:
    print("=" * 60)
    print("Semantic Memory — Setup")
    print("=" * 60)
    print()
    print("This script configures your agent workspace to connect to")
    print("a Supabase semantic-memory backend.")
    print()

    # 1. Collect Supabase project info
    url = _input_required("Supabase project URL (e.g. https://xyz.supabase.co): ")
    anon_key = _input_required("Supabase anon key: ")

    project_ref = _extract_project_ref(url)
    if not project_ref:
        print("WARNING: Could not extract project ref from URL. Automatic mode will not work.")

    # 2. Optional Management Token for automatic setup
    print()
    print("Optional: Supabase Management Token (PAT)")
    print("  Obtained at: https://supabase.com/dashboard/account/tokens")
    print("  Enables automatic migration application. Leave blank for manual setup.")
    pat = getpass.getpass("Management token (press Enter to skip): ").strip() or None

    # 3. Check database state via /init Edge Function
    print()
    print("Checking backend state...")
    try:
        status = _call_init_edge_function(url, anon_key)
    except httpx.HTTPStatusError as e:
        if e.response.status_code == 404:
            print("  The /init Edge Function is not deployed yet.")
            print("  You need to deploy the Edge Functions first.")
            status = {"status": "needs_setup", "message": "init function not found"}
        else:
            print(f"  Error contacting backend: {e}")
            status = {"status": "needs_setup", "message": str(e)}
    except Exception as e:
        print(f"  Error contacting backend: {e}")
        status = {"status": "needs_setup", "message": str(e)}

    if status.get("status") == "needs_setup":
        print()
        print("Backend is NOT fully configured.")
        print(f"  Reason: {status.get('message', 'unknown')}")
        print()

        migrations = _find_migrations()
        auto_ok = False

        if pat and project_ref and migrations:
            print("Attempting automatic setup via Management API...")
            all_ok = True
            for name, sql in migrations:
                if not _apply_migration_via_api(project_ref, pat, name, sql):
                    all_ok = False
                    break
            if all_ok:
                print("Automatic setup completed.")
                auto_ok = True
            else:
                print("Automatic setup failed. Switching to manual instructions.")
                print()

        if not auto_ok:
            print("MANUAL SETUP REQUIRED:")
            print()
            if migrations:
                print("1. Open your Supabase project SQL Editor")
                print("2. Run the following migrations in order:")
                print()
                for name, sql in migrations:
                    print(f"--- {name} ---")
                    print(sql)
                    print()
            else:
                print("1. Could not find migration files locally.")
                print("   Copy them from the infra repository into the SQL Editor.")
            print()
            print("3. Deploy Edge Functions:")
            print("   npx supabase functions deploy")
            print()
            print("After completing the above, re-run this script.")
            print()
            sys.exit(1)
    else:
        print("  Backend is ready.")
        if status.get("system_agent"):
            print("  System agent seeded.")
        else:
            print("  WARNING: System agent not found — seed may be needed.")

    # 4. Create or verify shared auth user
    print()
    print("Shared auth user (all agents use the same account)")
    email = _input_required("Email for shared agent account: ")

    import secrets
    default_password = secrets.token_urlsafe(16)
    password_input = getpass.getpass(
        f"Password [press Enter for auto-generated]: "
    ).strip()
    password = password_input if password_input else default_password
    if not password_input:
        print(f"  Generated password: {password}")

    print()
    print("Creating user via Supabase Auth...")
    try:
        # Use a raw HTTP call to sign up; we don't have supabase-py initialized yet
        resp = httpx.post(
            f"{url}/auth/v1/signup",
            headers={
                "apikey": anon_key,
                "Content-Type": "application/json",
            },
            json={"email": email, "password": password},
            timeout=30.0,
        )
        if resp.status_code in (200, 201):
            print("  User created successfully.")
        elif resp.status_code == 422 and "already" in resp.text.lower():
            print("  User already exists (OK).")
        else:
            print(f"  Warning: signup returned {resp.status_code}: {resp.text}")
            print("  You may need to confirm the email in the Supabase dashboard.")
    except Exception as e:
        print(f"  Error creating user: {e}")
        print("  You can create the user manually in the Supabase dashboard.")

    # 5. Save .env
    print()
    env_path = Path.cwd() / ".env"
    if env_path.exists():
        overwrite = input(f"{env_path} already exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite not in ("y", "yes"):
            print("  Skipped .env creation. Credentials:")
            print(f"    SUPABASE_URL={url}")
            print(f"    SUPABASE_ANON_KEY={anon_key}")
            print(f"    AGENT_EMAIL={email}")
            print(f"    AGENT_PASSWORD={password}")
            return

    _create_env_file(env_path, url, anon_key, email, password)
    print(f"  Saved credentials to {env_path}")

    # 6. Quick connection test
    print()
    print("Testing connection...")
    try:
        from dotenv import load_dotenv
        load_dotenv(env_path)

        from memory_client import MemoryClient
        client = MemoryClient()
        client.authenticate()
        print("  Authentication OK!")

        # Try a lightweight admin call
        agents = client.admin_action("list_agents", {})
        print(f"  Found {len(agents)} agent(s) in the database.")
        print()
        print("Setup complete. You can now use semantic memory.")
    except Exception as e:
        print(f"  Connection test failed: {e}")
        print("  Check your credentials and that the Edge Functions are deployed.")

    print()
    print("=" * 60)


if __name__ == "__main__":
    run_init()
