"""expand_numeric_precision_proposta_itens

Revision ID: 42558547f530
Revises: 030
Create Date: 2026-05-13 15:16:16.082838

Aumenta precisão de NUMERIC(15,4) → NUMERIC(20,4) em proposta_itens e
proposta_item_composicoes para suportar valores unitários acima de 10^11
provenientes do TCPO (ex: equipamentos de grande porte).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '42558547f530'
down_revision: Union[str, None] = '030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PI = "operacional.proposta_itens"
_PIC = "operacional.proposta_item_composicoes"
_P = "operacional.propostas"


def _alter(table: str, column: str, from_prec: tuple, to_prec: tuple) -> None:
    op.alter_column(
        table.split(".")[1],
        column,
        type_=sa.Numeric(*to_prec),
        schema=table.split(".")[0],
        existing_type=sa.Numeric(*from_prec),
        existing_nullable=True,
    )


def upgrade() -> None:
    cols_pi = [
        "quantidade",
        "custo_material_unitario",
        "custo_mao_obra_unitario",
        "custo_equipamento_unitario",
        "custo_direto_unitario",
        "custo_indireto_unitario",
        "preco_unitario",
        "preco_total",
    ]
    for col in cols_pi:
        _alter(_PI, col, (15, 4), (20, 4))

    cols_pic = [
        "custo_unitario_insumo",
        "custo_total_insumo",
    ]
    for col in cols_pic:
        _alter(_PIC, col, (15, 4), (20, 4))

    # Proposta totais
    for col in ("total_direto", "total_indireto", "total_geral"):
        _alter(_P, col, (15, 4), (20, 4))


def downgrade() -> None:
    cols_pi = [
        "quantidade",
        "custo_material_unitario",
        "custo_mao_obra_unitario",
        "custo_equipamento_unitario",
        "custo_direto_unitario",
        "custo_indireto_unitario",
        "preco_unitario",
        "preco_total",
    ]
    for col in cols_pi:
        _alter(_PI, col, (20, 4), (15, 4))

    cols_pic = [
        "custo_unitario_insumo",
        "custo_total_insumo",
    ]
    for col in cols_pic:
        _alter(_PIC, col, (20, 4), (15, 4))

    for col in ("total_direto", "total_indireto", "total_geral"):
        _alter(_P, col, (20, 4), (15, 4))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pc_item_vinculo_tcpo',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pc_cabecalho_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('origem_tabela', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('origem_registro_ref', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('servico_tcpo_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo_vinculo', sa.VARCHAR(length=30), server_default=sa.text("'AUTO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('confianca', sa.NUMERIC(precision=5, scale=4), server_default=sa.text("'1'::numeric"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['servico_tcpo_id'], ['referencia.base_tcpo.id'], name='pc_item_vinculo_tcpo_servico_tcpo_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pc_item_vinculo_tcpo_pkey'),
    sa.UniqueConstraint('pc_cabecalho_id', 'origem_tabela', 'origem_registro_ref', name='uq_pc_item_vinculo_origem')
    )
    op.create_index('ix_pc_item_vinculo_tcpo', 'pc_item_vinculo_tcpo', ['servico_tcpo_id'], unique=False)
    op.create_index('ix_pc_item_vinculo_pc', 'pc_item_vinculo_tcpo', ['pc_cabecalho_id'], unique=False)
    op.create_table('orcamento_item',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('orcamento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('servico_tcpo_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('codigo_origem', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unidade_medida', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'1'::numeric"), autoincrement=False, nullable=False),
    sa.Column('custo_unitario', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('custo_total', sa.NUMERIC(precision=15, scale=4), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('origem_item', sa.VARCHAR(length=30), server_default=sa.text("'TCPO'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], name='orcamento_item_orcamento_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_tcpo_id'], ['referencia.base_tcpo.id'], name='orcamento_item_servico_tcpo_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='orcamento_item_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_orcamento_item_servico', 'orcamento_item', ['servico_tcpo_id'], unique=False)
    op.create_index('ix_orcamento_item_orcamento', 'orcamento_item', ['orcamento_id'], unique=False)
    op.create_table('orcamento_item_composicao',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('orcamento_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('servico_pai_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('insumo_filho_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('descricao_insumo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unidade_medida', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('quantidade_consumo', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=False),
    sa.Column('custo_unitario', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('custo_total', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('fonte', sa.VARCHAR(length=30), server_default=sa.text("'SNAPSHOT'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['insumo_filho_id'], ['referencia.base_tcpo.id'], name='orcamento_item_composicao_insumo_filho_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orcamento_item_id'], ['orcamento_item.id'], name='orcamento_item_composicao_orcamento_item_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_pai_id'], ['referencia.base_tcpo.id'], name='orcamento_item_composicao_servico_pai_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='orcamento_item_composicao_pkey')
    )
    op.create_index('ix_orc_item_comp_orc_item', 'orcamento_item_composicao', ['orcamento_item_id'], unique=False)
    op.create_table('orcamento',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'EM_ELABORACAO'::character varying"), autoincrement=False, nullable=False),
    sa.Column('base_pc_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('aprovado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['operacional.clientes.id'], name='orcamento_cliente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orcamento_pkey'),
    sa.UniqueConstraint('cliente_id', 'codigo', name='uq_orcamento_cliente_codigo')
    )
    op.create_index('ix_orcamento_status', 'orcamento', ['status'], unique=False)
    op.create_index('ix_orcamento_cliente_id', 'orcamento', ['cliente_id'], unique=False)
    # ### end Alembic commands ###
